### ISSUE TITLE
Label alignment is messed up when a hint/error is provided but not visible

### ISSUE THREAD

**Issue by madebysid** [prisma/lens#188]
![Screenshot 2021-07-06 at 16 42 16](https://user-images.githubusercontent.com/7689783/124622502-77f7bc00-de7b-11eb-9454-cf9307453757.png)

This is in the Form story

**Comment by madebysid** [comment]
Turns out this is only happening to me in Firefox Developer Edition (90.0b12)

**Comment by luanvdw** [comment]
Can confirm that it does break on **Firefox Developer Edition (90.0b12)** Will investigate 👍
