### ISSUE TITLE
Add an `isLoading` prop to Button

### ISSUE THREAD

**Issue by madebysid** [prisma/lens#193]
Should disable the button and show a loader to the right of the button text

**Comment by ruheni** [comment]
Do we have a design for how this will look like? I think that the `Loader` won't be visible when the button is disabled.

**Comment by madebysid** [comment]
Might need input from @julietacurdi

**Comment by julietacurdi** [comment]
I recommend we add a loader to the left, inside the button. Here's an example:
- https://evergreen.segment.com/components/buttons
<img width="1158" alt="Screen Shot 2021-07-21 at 2 33 55 PM" src="https://user-images.githubusercontent.com/20726387/126533905-a42b36cb-6ead-4ddd-99b0-c06b6d29060a.png">


- https://elastic.github.io/eui/#/navigation/button#loading-state
<img width="279" alt="Screen Shot 2021-07-21 at 2 34 06 PM" src="https://user-images.githubusercontent.com/20726387/126533869-e5eb1b6e-9924-4f03-a423-d9e991dbd1e5.png">

**Comment by ruheni** [comment]
Thanks for making the fix @madebysid. 

One concern though, the loader is not visible when the button is using the `primary` variant. I was avoiding this, hence why I defaulted to using `secondary

<img width="148" alt="Screenshot 2021-07-26 at 12 10 28" src="https://user-images.githubusercontent.com/33921841/126964299-b98aecf8-3ec3-4d38-b1be-31418318257a.png">

**Comment by madebysid** [comment]
Yeah I changed the story to include all three variants. This invisible thing is a @julietacurdi question: https://prismalens.netlify.app/?path=/story/lens-button--with-loader

**Comment by ruheni** [comment]
From @julietacurdi's feedback, I made the assumption that the loading buttons would be of the secondary variant.

**Comment by madebysid** [comment]
Oh? I don't know if that's what she meant. Let's wait for her to confirm

**Comment by julietacurdi** [comment]
Yes so I think it would make sense for us to have only one disable stat and one loading state, all buttons defaulting to that one when disabled or loading. So we keep consistency on that regardless of the button and we make sure its accessible and dont have to cater for all the cases just 1. Loadings are also disabled so they should look like that just loading.

Here are some examples of DS that do that:
- https://www.mongodb.design/component/button/example/
- https://design.gitlab.com/components/button
- https://evergreen.segment.com/components/buttons
- https://elastic.github.io/eui/#/navigation/button#loading-state


If we have all disabled as a washed out version of the button, we can keep it like that and review later when i do the audit of the ds components. Im fine with that approach.
In that case, yes we need the spinner lighter
