### ISSUE TITLE
Improve Button Icon logic

### ISSUE THREAD

**Issue by luanvdw** [prisma/lens#227]
With the `<Button />` being able to accept/render icons. We can improve the rendering logic such that it can be used as an icon button as follows,

`<Button icon="copy" iconSize="sm" />`

As opposed to needing to import Button and Icon in order to create a Button Icon in the following manner,

```
<Button>
  <Icon name="copy" size="sm" />
</Button>
```

**Comment by madebysid** [comment]
IIUC that's exactly what happens right now, am I missing something?

**Comment by luanvdw** [comment]
> IIUC that's exactly what happens right now, am I missing something?

It was just minor spacing/rendering that was off in the event that an `Icon` should render in the absence of `{children}`

I created a PR for the update
