### ISSUE TITLE
Quiet variant for `Link`s

### ISSUE THREAD

**Issue by sdnts** [prisma/lens#275]
I've often seen us use the Next link component to avoid styling the Lens Link in Cloud. Let's introduce a `quiet` variant that will not style its children in any way and use that in Cloud.

This might also let us get rid of the `quiet` variant from `Button`s, which is often misused as an unstyled link (with an `onPress` that navigates you to a different page), which is an anti-pattern and hurts accessibility

**Comment by carlagn** [comment]
Can be based off the already existent `<Button variant="quiet" />`

**Comment by nilubava** [comment]
@luanvdw Could you pls review this and close the issue if stale
