### ISSUE TITLE
Select UI closes when at end of scroll

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/lens#30]
![2021-03-23 15 43 20](https://user-images.githubusercontent.com/284476/112208257-8b458b00-8bee-11eb-8ccc-44874262d958.gif)

After hitting the end with scrolling, scrolling some more automatically closes the item selection. Feels like a bug.

**Comment by madebysid** [comment]
Likely because the `Select` dropdown does not capture focus. After you reach the end, the next scroll event goes to the parent, which the dropdon treats as a page scroll (as it should), and so it closes.

**Comment by martzoukos** [comment]
This seems to not be applying any more or be fixed. 

This also seems to be consistent behavior with a native `select` [input](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select) where a scroll outside or at the end of the dropdown closes it.

**Comment by jasonkuhrt** [comment]
This is till happening for me. I really don't like the behaviour, happy to close if no else agrees but let's discuss at next sync meeting 🙏. I can "demo" the problem then too.

**Comment by carlagn** [comment]
Fixed/Stale:


https://user-images.githubusercontent.com/14851246/234834210-044aa724-dc92-4527-aa55-83058cf5df3f.mov
