### ISSUE TITLE
Cannot type into combo box to select value

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/lens#31]
Typing in a correct value and then tabbing out loses the value

![2021-03-23 21 59 36](https://user-images.githubusercontent.com/284476/112243089-5bfd4100-8c23-11eb-9199-c32556919e01.gif)

**Comment by madebysid** [comment]
AKA auto-select the first matching value. I'm not sure if this should happen. I'm of the opinion that you should have to mnually confirm a value to "select" it. Will leave the final decision to @julietacurdi

**Comment by martzoukos** [comment]
I'm +1 the above comment. I see similar behavior from other examples: https://material-ui.com/components/autocomplete/

**Comment by julietacurdi** [comment]
Agree with Sid and Spiros, lets keep the manual confirm

**Comment by madebysid** [comment]
Closing! Let me know if this WASN'T what you meant @jasonkuhrt
