### ISSUE TITLE
Cannot fuzzy-search a combo box

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/lens#32]
Typing in a value does not narrow down the list

![2021-03-23 21 59 36](https://user-images.githubusercontent.com/284476/112243089-5bfd4100-8c23-11eb-9199-c32556919e01.gif)

**Comment by madebysid** [comment]
Seems to be an issue only when data is input dynamically. Will check

Dynamic data: https://prismalens.netlify.app/?path=/story/lens-combobox--default-with-dynamic-data
Static data: https://prismalens.netlify.app/?path=/story/lens-combobox--default-with-static-data

**Comment by martzoukos** [comment]
Similar to https://github.com/prisma/lens/issues/31, check both when solution is implemented as they might both be fixed.
