### ISSUE TITLE
Change modal close-on-blur default 

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/lens#33]
- Original context in slack: https://prisma-company.slack.com/archives/G017LDGDWEL/p1616517306140300

- Current default is true, do close on blur which includes changing focus to another OS window

- Suggestion here is to flip the default

**Comment by carlagn** [comment]
Can't access the slack convo... @jasonkuhrt is this something still needed?

**Comment by nilubava** [comment]
Not relavant for Webdev
