### ISSUE TITLE
Broken hit area on select

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/lens#397]
![CleanShot 2022-05-06 at 10 39 49](https://user-images.githubusercontent.com/284476/167155638-53a9bc5b-124e-4650-b9ae-1e83020d1bf3.gif)

(this was in Chrome)

**Comment by harris2310** [comment]
Hello there, I could resolve this for you

**Comment by jasonkuhrt** [comment]
@harris2310 more than welcome thanks!

**Comment by harris2310** [comment]
Cool cool!

**Comment by carlagn** [comment]
Fixed here: https://github.com/harris2310/lens/commit/3325e84d8cb0f1f88fad58de216fe87e265b103a
