### ISSUE TITLE
Update to Email Newsletter on Footer

### ISSUE THREAD

**Issue by peterondesign** [prisma/lens#411]
### Description

We'd like to add the full name input to the newsletter

### Additional Context

Current Newsletter on Footer

<img width="1425" alt="Screenshot 2022-07-18 at 15 01 05" src="https://user-images.githubusercontent.com/36060650/179528403-091672a4-7b27-42e5-96e0-58262984bc31.png">

Proposed Newsletter on Footer

<img width="579" alt="Screenshot 2022-07-18 at 15 43 35" src="https://user-images.githubusercontent.com/36060650/179537064-23fae173-fdbc-4fcc-a85f-9b47b6687468.png">

States

<img width="556" alt="Screenshot 2022-07-18 at 15 44 09" src="https://user-images.githubusercontent.com/36060650/179537159-55890fe5-0dcd-4b75-9029-013e47300165.png">

Note: After form submission, button state changes to default on focus/hover of other form elements

Apply changes to mobile

<img width="367" alt="Screenshot 2022-07-18 at 15 45 07" src="https://user-images.githubusercontent.com/36060650/179537361-3d2a1261-61f4-4b71-8308-85d2dd06d846.png">

Figma link: https://www.figma.com/file/e7LXGWGpHnPjth5amUMgZW/Prisma-Website-Drafts?node-id=5664%3A3755

**Comment by meletj** [comment]
@carlagn for this PR, did Peter also provide you with the designs for the newsletter sign up fields on community page, on blog articles and on prisma.io/newsletter?
