### ISSUE TITLE
Web: Right click and open the header tabs

### ISSUE THREAD

**Issue by nilubava** [prisma/lens#435]
I can not use middle click (or right click and then context menu) to open the product pages in new tabs

https://prisma-company.slack.com/archives/C601F4CF8/p1654105174862969

**Comment by carlagn** [comment]
Doesn't happen anymore but can be converted into removing the `user-select` css property when right-clicking on the menu item:

<img width="497" alt="Screenshot 2023-04-26 at 17 52 23" src="https://user-images.githubusercontent.com/14851246/234647323-6872947f-0e75-4691-b0b8-5fb08ca14a1d.png">
