### ISSUE TITLE
Use `useHover` for hover states rather than Tailwind's `hover:` classes

### ISSUE THREAD

**Issue by sdnts** [prisma/lens#53]
It is needed to standardize hover states across devices (mobile and desktop)

**Comment by carlagn** [comment]
Files still using tailwind's `hover:*`:
https://github.com/prisma/lens/blob/6b1994e5a62109b3d75341cff6c13982c53c9a92/src/cloud/project-picker/ProjectPicker.tsx#L325
https://github.com/prisma/lens/blob/6b1994e5a62109b3d75341cff6c13982c53c9a92/src/components/accordion/Accordion.tsx#L87
https://github.com/prisma/lens/blob/6b1994e5a62109b3d75341cff6c13982c53c9a92/src/components/checkbox/Checkbox.tsx#L65
https://github.com/prisma/lens/blob/6b1994e5a62109b3d75341cff6c13982c53c9a92/src/components/menu/Menu.tsx#L332

**Comment by nilubava** [comment]
@luanvdw Could you pls review this and close the issue if stale
