### ISSUE TITLE
Plan out tailwind rollout

### ISSUE THREAD

**Issue by nilubava** [prisma/lens#68]
Plan out how to integrate Lens navbar into docs and blog 
- tailwind presets override docs styles
https://github.com/prisma/docs/pull/2297

**Comment by hrescak** [comment]
To the websites
Notes:
- First thing is investigate if tailwind can live together with our styled components (in homepage, blog and docs), and how much of a performance hit is it.
  - If it's OK, change footer and header to tailwind in lens and remove styled components from lens, and start incremental adoption in different repositiories
  - for every repository this is a great opportunity to review components and abstractions and start re-doing the repo specific components in tailwind
  - move to re-doing the pages to tailwind, starting with the highest foot-traffic ones to make them as fast as possible as soon as possible
- If it's not OK, let's circle back
