### ISSUE TITLE
Update Terms & Privacy Link

### ISSUE THREAD

**Issue by jdmachogg** [prisma/lens#9]
https://github.com/prisma/lens/blob/ab48c5654127991413e5eaab0d5df67f9ca40476/src/components/footer.tsx#L233-L235

Can we update this to: https://www.notion.so/prismaio/Terms-Privacy-5b5b9938b3a941ccb2ad97eaf5524c07

**Comment by Jolg42** [comment]
Done in https://github.com/prisma/lens/pull/10
