### ISSUE TITLE
Cannot click outside select input or press ESC to close it.

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/lens#91]
![image](https://user-images.githubusercontent.com/284476/117340154-971fa080-ae6e-11eb-8668-8970267213a7.png)

If this is a cloud issue (e.g. props configuration) then just transfer this issue to cloud repo.

**Comment by ruheni** [comment]
So, this only seems to happen when the Select component has a pre-selected option. 🤔

**Comment by carlagn** [comment]
Doesn't close on ESC. Able to click outside.

**Comment by ruheni** [comment]
I think this PR: https://github.com/prisma/lens/pull/312 may have resolve the issue 🤔
